In [1]:
import numpy as np

In [4]:
arr = np.arange(0,30,3)

In [5]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
arr[:3]

array([0, 3, 6])

In [8]:
arr[2:5]

array([ 6,  9, 12])

In [9]:
arr[5:] = 100

In [10]:
arr

array([  0,   3,   6,   9,  12, 100, 100, 100, 100, 100])

In [44]:
mat = np.arange(50).reshape((5,10))

In [45]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [34]:
mat.shape

(5, 10)

In [35]:
mat[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [36]:
mat2 = mat[:3]

In [37]:
mat2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [38]:
mat2[:3] = 100

<h3>Ao fazer a atribuição dos elementos das três primeiras linhas da matriz à <i>mat2</i>, é feita uma referência e não uma cópia, logo qualquer atribuição em <i>mat2</i> refletirá em <i>mat</i></h3>

In [39]:
mat2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [40]:
mat

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

<h3>Para uma cópia deve-se utilizar do método copy()</h3>

In [46]:
mat2 = mat[:3].copy()

In [47]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

<h3>Aplicando fatiamento em linhas e colunas respectivamente</h3>

In [48]:
mat[1:3,2:8]

array([[12, 13, 14, 15, 16, 17],
       [22, 23, 24, 25, 26, 27]])

<h3>Selecionando dados que atendem a uma determinada condição diretamente</h3>

In [49]:
mat > 25

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [50]:
bol = mat > 25

In [51]:
mat[bol]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [53]:
array = np.linspace(0,100, 30)

In [54]:
array

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [57]:
array = array.reshape((3,10))

In [58]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [59]:
array.shape

(3, 10)

In [60]:
array[:2, 2]

array([ 6.89655172, 41.37931034])