In [1]:
import numpy as np

In [2]:
minha_lista = [1, 2, 3]

In [3]:
minha_lista

[1, 2, 3]

In [5]:
np.array(minha_lista)

array([1, 2, 3])

In [6]:
minha_matriz = [[1,2,3], [4,5,6], [7,8,9]]

In [7]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(2)

array([0., 0.])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

<h3>Cria uma matriz identidade<h3>

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<h3>Cria uma listagem de número igualmente espaçados de uma série</h3>

In [25]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [26]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

<h3>Selecão de números aleátorios entre 0 e 1 com mesma probabilidade de serem selecionados.</h3>

In [30]:
np.random.rand(5,4) * 100

array([[39.90808821, 39.12524221, 98.12405173, 95.15307201],
       [58.73257304, 95.87531192, 58.13603314, 11.45235884],
       [19.53365919, 73.3770297 , 43.14818268, 80.24975407],
       [75.7489805 , 17.25749166, 21.81085977, 62.39042352],
       [74.05666034, 21.05774405,  5.77385738, 34.4875532 ]])

In [28]:
np.random.randn(4)

array([-0.65557013,  0.94543758, -1.08083283, -0.40135142])

In [31]:
np.random.randint(0,100,10)

array([23, 69, 32, 11, 91, 72, 27, 43, 82, 62])

In [43]:
arr = np.random.rand(25)

In [44]:
arr

array([0.5200871 , 0.95308185, 0.81205384, 0.93198241, 0.76555405,
       0.13996922, 0.38466542, 0.37933726, 0.90905148, 0.87258271,
       0.53565564, 0.09879761, 0.12087365, 0.82723517, 0.89603305,
       0.12403329, 0.12537247, 0.65551231, 0.48566899, 0.3088526 ,
       0.33312667, 0.19001425, 0.04752956, 0.8505351 , 0.66888577])

In [45]:
arr.shape

(25,)

In [46]:
arr = arr.reshape((5,5))

In [47]:
arr

array([[0.5200871 , 0.95308185, 0.81205384, 0.93198241, 0.76555405],
       [0.13996922, 0.38466542, 0.37933726, 0.90905148, 0.87258271],
       [0.53565564, 0.09879761, 0.12087365, 0.82723517, 0.89603305],
       [0.12403329, 0.12537247, 0.65551231, 0.48566899, 0.3088526 ],
       [0.33312667, 0.19001425, 0.04752956, 0.8505351 , 0.66888577]])

In [48]:
arr.shape

(5, 5)

In [49]:
arr.max()

0.9530818470613034

In [50]:
arr.min()

0.047529560951562466

In [51]:
arr.argmax()

1

In [52]:
arr.argmin()

22